spring:
  application:
    name: task-tracker
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: name
    password: password
  sql:
    init:
      schema-locations: classpath:initial-db-schema.sql
      mode: always
  h2:
    console:
      enabled: true
server:
  port: 4000